// テスト用の最小キャラデータ。AR 720rpm・60 発・リロード 1 秒・武器倍率 13.65% を既定にする。
import type { CharacterData, ShotParams } from '../types.ts';

export function makeCharacter(shot: Partial<ShotParams> = {}, overrides: Partial<CharacterData> = {}): CharacterData {
  const skill = { id: 0, name: { ja: '', en: '' }, description: { ja: '', en: '' }, values: [] };
  return {
    resourceId: 1,
    name: { ja: 'テスト', en: 'Test' },
    rarity: 'SSR',
    class: 'Attacker',
    corporation: 'ELYSION',
    element: 'Fire',
    weaponType: 'AR',
    burstStep: 'Step3',
    levelCurve: { attack: [1000], hp: [10000], defence: [100] },
    statEnhance: {
      gradeRatio: 200,
      gradeAttack: 20,
      gradeHp: 3000,
      gradeDefence: 100,
      coreAttack: 200,
      coreHp: 200,
      coreDefence: 200,
    },
    crit: { rate: 0.15, damage: 1.5 },
    bonusRange: { min: 25, max: 45 },
    shot: {
      damage: 1365,
      shotCount: 1,
      muzzleCount: 1,
      maxAmmo: 60,
      reloadTime: 1,
      reloadBullet: 1,
      rateOfFire: 720,
      endRateOfFire: 720,
      rateOfFireChangePerShot: 0,
      rateOfFireResetTime: 0,
      chargeTime: 0,
      fullChargeDamage: 1,
      coreDamageRate: 2,
      inputType: 'DOWN',
      fireType: 'Instant',
      penetration: 0,
      maintainFireStance: 0,
      uptypeFireTiming: 0,
      targetBurstEnergyPerShot: 4000,
      burstEnergyPerShot: 2000,
      fullChargeBurstEnergy: 1,
      ...shot,
    },
    burstSkill: { cooldownSeconds: 40, nextStep: 'StepFull', durationSeconds: 10 },
    skills: { skill1: skill, skill2: skill, burst: skill },
    ...overrides,
  };
}
